### ISSUE TITLE
cannot load bats-support

### ISSUE THREAD

**Issue by kale1d0code** [bats-core/bats-action#12]
I've added the devcontainer feature and am not able to load bats support or bats bats-assert.

these lines don't work in my test files
load 'test_helper/bats-support/load'
load 'test_helper/bats-assert/load'

**Comment by kale1d0code** [comment]
I read through the documentation.

the locations of bats-support and bats-assert should be updated to:
'/usr/lib/bats/bats-support/load' and '/usr/lib/bats/bats-assert/load'

**Comment by brokenpip3** [comment]
> I read through the documentation.
> 
> the locations of bats-support and bats-assert should be updated to: '/usr/lib/bats/bats-support/load' and '/usr/lib/bats/bats-assert/load'

Hi :wave: 

are you sure? in the action tests we use `/usr/lib` as BATS_LIB_PATH and is working correctly, example [here](https://github.com/bats-core/bats-action/blob/73f0f7d34ec09278ce76030c105fc6a8ddb1d726/.github/workflows/test-local-action.yaml#L19).

Btw you are using the old way of loading the libraries:

if you expose the BATS_LIB_PATH env with value the base path where the libraries has been installed (in this case and by default it will be `/usr/lib`) then you can use the bats function `bats_load_library` to load the libraries.

You can check the action example [here](https://github.com/jenkinsci/kubernetes-operator/blob/e40032497b9bea6bc5070b35c31f133d6b364447/test/bats/test_helper.bash#L2-L6)

**Comment by brokenpip3** [comment]
@kale1d0code are you satisfied with the answer? can I close the issue?

**Comment by brokenpip3** [comment]
Since there were no answer I'm going to close this issue, feel free to comment back, I will reopen it if necessary.
