### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by tbutler-qontigo** [bats-core/bats-action#13]
Hi
Trying to use this in a github action on `windows-latest` it fails due to lack of `sudo`:
```
VERSION=0.3.0
  DESTDIR=D:\a\devops-gh-actions\devops-gh-actions/_buildtools/bats/1.11.0/bats-support
  TEMPDIR="/tmp/bats-support"
  url="[https://github.com/bats-core/bats-support/archive/refs/tags/v${VERSION}.tar.gz](https://github.com/bats-core/bats-support/archive/refs/tags/v$%7BVERSION%7D.tar.gz)"
  
  mkdir -p ${TEMPDIR}
  [[ "${DESTDIR}" == "$HOME"* ]] && CMD="" || CMD="sudo"
  ${CMD} mkdir -p ${DESTDIR}/src/
  curl -sL ${url} | tar xz -C ${TEMPDIR} --strip-components 1 && cd ${TEMPDIR}
  # Archlinux style, except that we are not in a fakeroot env
  ${CMD} install -Dm755 load.bash ${DESTDIR}/load.bash
  for fn in src/*.bash; do
    ${CMD} install -Dm755 $fn \
       ${DESTDIR}/src/$(basename $fn)
  done
  echo "Bats Support v$VERSION installed in $DESTDIR"
  echo "support-installed=true" >> $GITHUB_OUTPUT
  # Cleanup bats-support if required
  [[ "true" = "true"  ]] && rm -rf ${TEMPDIR} || exit 0
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
D:\a\_temp\f5e99e24-da2b-4206-a0ee-ba2419854757.sh: line 8: sudo: command not found
```
I am installing in `${{ github.workspace }}/_buildtools/bats-support`

**Comment by brokenpip3** [comment]
Hi :wave: 

honestly never tried on windows runners :D 

and yes it will probably not work 'cause [this](https://github.com/bats-core/bats-action/blob/73f0f7d34ec09278ce76030c105fc6a8ddb1d726/action.yaml#L171) check will check for $HOME, in windows runners seems `C:\Users\runneradmin` probably bash on windows is not capable to expand the home directory? not sure since I can't test it on my own (no win systems).

Anyway should be not too so complex to fix, so we can support windows runners as well :)
Will try a branch and let you know

**Comment by tbutler-qontigo** [comment]
Hi
Yes it can work with using the `$HOME` folder to avoid the need to try to load sudo but IMO it would be better if it can work with any folder like it can on linux

You could have your CI tests run on `windows-latest` as well as `ubuntu-latest` to validate your changes work - so no local windows required ;)

thanls

**Comment by brokenpip3** [comment]
>You could have your CI tests run on windows-latest as well as ubuntu-latest to validate your changes work - so no local windows required ;)

yup that's my plan, I was also thinking to add the macos in the matrix so we can assure that we support that os as well

**Comment by brokenpip3** [comment]
Sorry I had few free cycles these days, will come back to this as soon I will find enough time

**Comment by tbutler-qontigo** [comment]
np, thanks for the update

**Comment by strick-j** [comment]
I am seeing a similar action on ubuntu-latest and ubuntu 20.04. Am I missing something?
`Run bats-core/bats-action@2.0.0
Run actions/cache@v4
/usr/bin/docker exec  13256a531eeaf46aedcf61e26c6a1f92ef3a46bc6c8c6f158dfdb0bd1a05445c sh -c "cat /etc/*release | grep ^ID"
Cache not found for input keys: Linux-bats-
Run # In $HOME to avoid sudo requirements
Installed Bats to /github/home/.local/share/bats/bin/bats
Bats v1.11.0 installed in /github/home/.local/share/bats
Run actions/cache@v4
/usr/bin/docker exec  13256a5[31](https://github.com/strick-j/autohtml5gw/actions/runs/10287750175/job/28471550552#step:5:33)eeaf46aedcf61e26c6a1f92ef3a46bc6c8c6f158dfdb0bd1a05445c sh -c "cat /etc/*release | grep ^ID"
Cache not found for input keys: Linux-bats-support-0.3.0
Run VERSION=0.3.0
  VERSION=0.3.0
  DESTDIR=/home/runner/work/autohtml5gw/autohtml5gw/test/libs/bats-support
  TEMPDIR="/tmp/bats-support"
  url="https://github.com/bats-core/bats-support/archive/refs/tags/v${VERSION}.tar.gz"
  
  mkdir -p ${TEMPDIR}
  [[ "${DESTDIR}" == "$HOME"* ]] && CMD="" || CMD="sudo"
  ${CMD} mkdir -p ${DESTDIR}/src/
  curl -sL ${url} | tar xz -C ${TEMPDIR} --strip-components 1 && cd ${TEMPDIR}
  # Archlinux style, except that we are not in a fakeroot env
  ${CMD} install -Dm[75](https://github.com/strick-j/autohtml5gw/actions/runs/10287750175/job/28471550552#step:5:79)5 load.bash ${DESTDIR}/load.bash
  for fn in src/*.bash; do
    ${CMD} install -Dm755 $fn \
       ${DESTDIR}/src/$(basename $fn)
  done
  echo "Bats Support v$VERSION installed in $DESTDIR"
  echo "support-installed=true" >> $GITHUB_OUTPUT
  # Cleanup bats-support if required
  [[ "true" = "true"  ]] && rm -rf ${TEMPDIR} || exit 0
  shell: bash --noprofile --norc -e -o pipefail {0}
/__w/_temp/a49bc454-f3a5-4cdf-a2df-f554acaf1a50.sh: line 8: sudo: command not found`

**Comment by airtonix** [comment]
https://github.com/microsoft/sudo is a thing. but you need to be using powershell (also where `$HOME` is a thing).

**Comment by brokenpip3** [comment]
> https://github.com/microsoft/sudo is a thing. but you need to be using powershell (also where `$HOME` is a thing).

thanks for the info! however bats needs bash, I will try to just execute with `bash` with windows since it seems that is supported :)
(and macos as well)

**Comment by airtonix** [comment]
Win bash is also a thing. I find it's better than gitbash

**Comment by brokenpip3** [comment]
@tbutler-qontigo @airtonix: if you want to test this PR seems that is working for windows, you can test it with:

```bash
       - name: Setup Bats and bats libs
         uses: bats-core/bats-action@feat-support-windows-mac
```
I still to fix the macos running cache hit and description/readme but it seems usable from my pov, at least by using windows :)

Let me know in any case

**Comment by brokenpip3** [comment]
Now is work-ish, if you have spare time to test it will be great :)

**Comment by brokenpip3** [comment]
It's ready to be tested :)

**Comment by tbutler-qontigo** [comment]
@brokenpip3 Apologies for the delay - I was swamped with other stuff.
I can confirm this is now working - thanks!

**Comment by brokenpip3** [comment]
great! thanks for the feedback, the `3.0.0` is out and contains all these changes
