### ISSUE TITLE
add runner.arch cache key in bats-action

### ISSUE THREAD

**Issue by akhilerm** [bats-core/bats-action#16]
Currently the bats-action caches the binary with the key [`{{ runner.os }}-bats-${{ inputs.bats-version }}`](https://github.com/bats-core/bats-action/blob/main/action.yaml#L112). This can cause issues with cacheing in CI were multiplatform setup is used. Ref: https://github.com/opencontainers/runc/actions/runs/11013141253/job/30588072588?pr=4405#step:17:23.  

The cache key should also have an entry for  `{{ runner.arch }}` along with OS.

**Comment by brokenpip3** [comment]
`2.1.0` just released, thanks @akhilerm
