### ISSUE TITLE
release 2.1.0 does not work on ubuntu-20.04

### ISSUE THREAD

**Issue by akhilerm** [bats-core/bats-action#18]
https://github.com/bats-core/bats-action/pull/14 added support for retrying when downloading bats using the `--retry-all-errors` flag. But this flag is not present on the curl that is installed in ubuntu-20.04 runner machine.

Ref for the failure: https://github.com/akhilerm/release-test/actions/runs/11030089600/job/30633923578#step:3:60

**Comment by brokenpip3** [comment]
`2.1.1` is out and it's supporting 20.04 as well, let me know

**Comment by lifubang** [comment]
> `2.1.1` is out and it's supporting 20.04 as well, let me know

👍 Thanks very much!

**Comment by brokenpip3** [comment]
yw!
